version: "3.9"
services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'spaceship_db'
      MYSQL_ROOT_PASSWORD: 'password'
    networks:
      - default
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: